// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEQuEPhvTRKLGAClcazSQItDzKO_sijcQ',
    appId: '1:416329553525:web:bfb6dd0698d96164504a3c',
    messagingSenderId: '416329553525',
    projectId: 'task-d4664',
    authDomain: 'task-d4664.firebaseapp.com',
    storageBucket: 'task-d4664.appspot.com',
    measurementId: 'G-GWBWPT9ZXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG2kdzBYa27wBBHPd_KrnmuYVyld2TEfE',
    appId: '1:416329553525:android:0b379fed9c627fb9504a3c',
    messagingSenderId: '416329553525',
    projectId: 'task-d4664',
    storageBucket: 'task-d4664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCjPw3dZVyHgXV_U2617WQqYqCkUDPWiA',
    appId: '1:416329553525:ios:5ff740fa80553b98504a3c',
    messagingSenderId: '416329553525',
    projectId: 'task-d4664',
    storageBucket: 'task-d4664.appspot.com',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCjPw3dZVyHgXV_U2617WQqYqCkUDPWiA',
    appId: '1:416329553525:ios:2bc764ce6be53033504a3c',
    messagingSenderId: '416329553525',
    projectId: 'task-d4664',
    storageBucket: 'task-d4664.appspot.com',
    iosBundleId: 'com.example.hello.RunnerTests',
  );
}
